// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StratSphere.Infrastructure.Data;

#nullable disable

namespace StratSphere.Infrastructure.Migrations
{
    [DbContext(typeof(StratSphereDbContext))]
    [Migration("20251207225706_AddSubleagueDivision")]
    partial class AddSubleagueDivision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StratSphere.Core.Entities.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SubleagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubleagueId");

                    b.HasIndex("LeagueId", "SubleagueId", "Name")
                        .IsUnique();

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("AllowTrading")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPick")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CurrentPickDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentTeamOnClock")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PickTimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SnakeDraft")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.DraftOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginalTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PositionInRound")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("OriginalTeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("DraftOrders");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoPick")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OriginalTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallPickNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickMadeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "OverallPickNumber")
                        .IsUnique();

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GameNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlayoff")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PlayoffRound")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveRosterSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RosterSize")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseDH")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.LeagueMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "UserId")
                        .IsUnique();

                    b.ToTable("LeagueMembers");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.MlbAllstar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GP")
                        .HasColumnType("text");

                    b.Property<string>("GameId")
                        .HasColumnType("text");

                    b.Property<string>("GameNum")
                        .HasColumnType("text");

                    b.Property<string>("LgId")
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("StartingPos")
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MlbAllstars");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.MlbBatting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AB")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BA")
                        .HasColumnType("numeric");

                    b.Property<int?>("BB")
                        .HasColumnType("integer");

                    b.Property<int?>("CS")
                        .HasColumnType("integer");

                    b.Property<int?>("Doubles")
                        .HasColumnType("integer");

                    b.Property<int?>("GIDP")
                        .HasColumnType("integer");

                    b.Property<int?>("Games")
                        .HasColumnType("integer");

                    b.Property<int?>("HBP")
                        .HasColumnType("integer");

                    b.Property<int?>("HR")
                        .HasColumnType("integer");

                    b.Property<int?>("Hits")
                        .HasColumnType("integer");

                    b.Property<int?>("IBB")
                        .HasColumnType("integer");

                    b.Property<string>("LgId")
                        .HasColumnType("text");

                    b.Property<decimal?>("OBP")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OPS")
                        .HasColumnType("numeric");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int?>("RBIs")
                        .HasColumnType("integer");

                    b.Property<int?>("Runs")
                        .HasColumnType("integer");

                    b.Property<int?>("SB")
                        .HasColumnType("integer");

                    b.Property<int?>("SF")
                        .HasColumnType("integer");

                    b.Property<int?>("SH")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SLG")
                        .HasColumnType("numeric");

                    b.Property<int?>("SO")
                        .HasColumnType("integer");

                    b.Property<int>("Stint")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<int?>("Triples")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MlbBattings");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.MlbFielding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("A")
                        .HasColumnType("integer");

                    b.Property<int?>("DP")
                        .HasColumnType("integer");

                    b.Property<int?>("E")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Fpct")
                        .HasColumnType("numeric");

                    b.Property<int?>("GS")
                        .HasColumnType("integer");

                    b.Property<int?>("Games")
                        .HasColumnType("integer");

                    b.Property<int?>("InnOuts")
                        .HasColumnType("integer");

                    b.Property<int?>("Lg")
                        .HasColumnType("integer");

                    b.Property<int?>("PO")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("Pos")
                        .HasColumnType("text");

                    b.Property<int>("Stint")
                        .HasColumnType("integer");

                    b.Property<int?>("Tm")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MlbFieldings");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.MlbHallOfFame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ballots")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<int?>("NeededVotes")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<decimal?>("VotePct")
                        .HasColumnType("numeric");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int?>("YearElected")
                        .HasColumnType("integer");

                    b.Property<string>("YearOnBallot")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MlbHallOfFames");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.MlbPeople", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char?>("Bats")
                        .HasColumnType("character(1)");

                    b.Property<string>("BbRefUrl")
                        .HasColumnType("text");

                    b.Property<string>("BirthCity")
                        .HasColumnType("text");

                    b.Property<string>("BirthCountry")
                        .HasColumnType("text");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("integer");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("integer");

                    b.Property<string>("BirthState")
                        .HasColumnType("text");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("DeathCity")
                        .HasColumnType("text");

                    b.Property<string>("DeathCountry")
                        .HasColumnType("text");

                    b.Property<int?>("DeathDay")
                        .HasColumnType("integer");

                    b.Property<int?>("DeathMonth")
                        .HasColumnType("integer");

                    b.Property<string>("DeathState")
                        .HasColumnType("text");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Debut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinalGame")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("NameFirst")
                        .HasColumnType("text");

                    b.Property<string>("NameGiven")
                        .HasColumnType("text");

                    b.Property<string>("NameLast")
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RetroSheetId")
                        .HasColumnType("text");

                    b.Property<char?>("Throws")
                        .HasColumnType("character(1)");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MlbPeople");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.MlbPitching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AREA")
                        .HasColumnType("integer");

                    b.Property<int?>("BB")
                        .HasColumnType("integer");

                    b.Property<int?>("BK")
                        .HasColumnType("integer");

                    b.Property<int?>("CG")
                        .HasColumnType("integer");

                    b.Property<int?>("ER")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ERA")
                        .HasColumnType("numeric");

                    b.Property<int?>("G")
                        .HasColumnType("integer");

                    b.Property<int?>("GS")
                        .HasColumnType("integer");

                    b.Property<int?>("H")
                        .HasColumnType("integer");

                    b.Property<int?>("HBP")
                        .HasColumnType("integer");

                    b.Property<int?>("HR")
                        .HasColumnType("integer");

                    b.Property<int?>("IBB")
                        .HasColumnType("integer");

                    b.Property<int?>("IPouts")
                        .HasColumnType("integer");

                    b.Property<int?>("K")
                        .HasColumnType("integer");

                    b.Property<int?>("L")
                        .HasColumnType("integer");

                    b.Property<string>("LgId")
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int?>("SHO")
                        .HasColumnType("integer");

                    b.Property<int?>("SV")
                        .HasColumnType("integer");

                    b.Property<int>("Stint")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<int?>("W")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WHIP")
                        .HasColumnType("numeric");

                    b.Property<int?>("WP")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MlbPitchings");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.MlbTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtBats")
                        .HasColumnType("integer");

                    b.Property<int?>("Attendance")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BA")
                        .HasColumnType("numeric");

                    b.Property<int?>("BPF")
                        .HasColumnType("integer");

                    b.Property<int?>("BbRef")
                        .HasColumnType("integer");

                    b.Property<int?>("BestRank")
                        .HasColumnType("integer");

                    b.Property<int?>("CaughtStealing")
                        .HasColumnType("integer");

                    b.Property<string>("DivId")
                        .HasColumnType("text");

                    b.Property<int?>("Doubles")
                        .HasColumnType("integer");

                    b.Property<int?>("E")
                        .HasColumnType("integer");

                    b.Property<int?>("Errs")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Fpct")
                        .HasColumnType("numeric");

                    b.Property<int?>("Games")
                        .HasColumnType("integer");

                    b.Property<int?>("GamesAway")
                        .HasColumnType("integer");

                    b.Property<int?>("GamesHome")
                        .HasColumnType("integer");

                    b.Property<int?>("Hits")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeRuns")
                        .HasColumnType("integer");

                    b.Property<string>("League")
                        .HasColumnType("text");

                    b.Property<int?>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Name_park_ref")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OBP")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OPS")
                        .HasColumnType("numeric");

                    b.Property<int?>("PPF")
                        .HasColumnType("integer");

                    b.Property<string>("Park")
                        .HasColumnType("text");

                    b.Property<int?>("Pitchers")
                        .HasColumnType("integer");

                    b.Property<int?>("RankDiv")
                        .HasColumnType("integer");

                    b.Property<int?>("RankLg")
                        .HasColumnType("integer");

                    b.Property<int?>("Runs")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SLG")
                        .HasColumnType("numeric");

                    b.Property<int?>("StolenBases")
                        .HasColumnType("integer");

                    b.Property<int?>("StrikeOuts")
                        .HasColumnType("integer");

                    b.Property<string>("TeamBbRef")
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .HasColumnType("text");

                    b.Property<int?>("Triples")
                        .HasColumnType("integer");

                    b.Property<int?>("Wins")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MlbTeams");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatsHand")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentMlbOrg")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CurrentMlbTeam")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MlbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MlbamId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PrimaryPosition")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryPositions")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StratCardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("StratYear")
                        .HasColumnType("integer");

                    b.Property<string>("ThrowsHand")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MlbId");

                    b.HasIndex("MlbamId");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.PlayerStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AtBats")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BB9")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BattingAverage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Doubles")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ERA")
                        .HasColumnType("numeric");

                    b.Property<int?>("EarnedRuns")
                        .HasColumnType("integer");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int?>("Hits")
                        .HasColumnType("integer");

                    b.Property<int?>("HitsAllowed")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeRuns")
                        .HasColumnType("integer");

                    b.Property<decimal?>("InningsPitched")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("K9")
                        .HasColumnType("numeric");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("Losses")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OPS")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OnBasePercentage")
                        .HasColumnType("numeric");

                    b.Property<int?>("PitchingStrikeouts")
                        .HasColumnType("integer");

                    b.Property<int?>("PitchingWalks")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RBI")
                        .HasColumnType("integer");

                    b.Property<int?>("Runs")
                        .HasColumnType("integer");

                    b.Property<int?>("Saves")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SluggingPercentage")
                        .HasColumnType("numeric");

                    b.Property<int?>("StolenBases")
                        .HasColumnType("integer");

                    b.Property<int?>("Strikeouts")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.Property<int?>("Triples")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WAR")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WHIP")
                        .HasColumnType("numeric");

                    b.Property<int?>("Walks")
                        .HasColumnType("integer");

                    b.Property<int?>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.RosterEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AcquiredVia")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ContractSalary")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int?>("ContractYearRemaining")
                        .HasColumnType("integer");

                    b.Property<int?>("ContractYears")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RosterPosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "PlayerId")
                        .IsUnique();

                    b.ToTable("RosterEntries");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.ScoutingReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArmTool")
                        .HasColumnType("integer");

                    b.Property<int?>("ChangeupTool")
                        .HasColumnType("integer");

                    b.Property<string>("Comparable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ControlTool")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurveballTool")
                        .HasColumnType("integer");

                    b.Property<string>("ETA")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("FastballTool")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldingTool")
                        .HasColumnType("integer");

                    b.Property<int?>("HitTool")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("OverallGrade")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PotentialGrade")
                        .HasColumnType("integer");

                    b.Property<int?>("PowerTool")
                        .HasColumnType("integer");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ScoutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScoutedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SliderTool")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeedTool")
                        .HasColumnType("integer");

                    b.Property<string>("Strengths")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Weaknesses")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ScoutedByUserId");

                    b.ToTable("ScoutingReports");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrentSeason")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Year")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.StandingsEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DivisionName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DivisionRank")
                        .HasColumnType("integer");

                    b.Property<decimal?>("GamesBack")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int?>("Last10Losses")
                        .HasColumnType("integer");

                    b.Property<int?>("Last10Wins")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LeagueRank")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int?>("RunsAllowed")
                        .HasColumnType("integer");

                    b.Property<int?>("RunsScored")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Streak")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Ties")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WinningPercentage")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("StandingsEntries");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.StratPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AtBats")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bats")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<decimal?>("ContractCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentSeasonWar")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("GamesStarted")
                        .HasColumnType("integer");

                    b.Property<decimal?>("InningsPitched")
                        .HasColumnType("decimal(6,1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOn40Man")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("MlbPlayerId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PreviousSeasonWar")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PrimaryPosition")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("QualifyingOffer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SignedInfo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("StratTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Throws")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("IsActive");

                    b.HasIndex("LeagueId");

                    b.HasIndex("MlbPlayerId");

                    b.HasIndex("StratTeamId");

                    b.ToTable("StratPlayers");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.StratTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("RosterCount40Man")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("TotalRosterCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation");

                    b.HasIndex("IsActive");

                    b.HasIndex("LeagueId");

                    b.HasIndex("LeagueId", "Abbreviation")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("StratTeams");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Subleague", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.ToTable("Subleagues");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Conference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DivisionName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubleagueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SubleagueId");

                    b.HasIndex("LeagueId", "Abbreviation")
                        .IsUnique();

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DraftPickNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("DraftRound")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("OtherTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TransactionGroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("OtherTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Division", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Subleague", "Subleague")
                        .WithMany("Divisions")
                        .HasForeignKey("SubleagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Subleague");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Draft", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany("Drafts")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.DraftOrder", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.Draft", "Draft")
                        .WithMany("DraftOrder")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Team", "OriginalTeam")
                        .WithMany()
                        .HasForeignKey("OriginalTeamId");

                    b.HasOne("StratSphere.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("League");

                    b.Navigation("OriginalTeam");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Player", "Player")
                        .WithMany("DraftSelections")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StratSphere.Core.Entities.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("League");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.GameResult", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Season", "Season")
                        .WithMany("Games")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.LeagueMember", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.User", "User")
                        .WithMany("LeagueMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.PlayerStats", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.RosterEntry", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Player", "Player")
                        .WithMany("RosterEntries")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.ScoutingReport", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Player", "Player")
                        .WithMany("ScoutingReports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.User", "ScoutedBy")
                        .WithMany()
                        .HasForeignKey("ScoutedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Player");

                    b.Navigation("ScoutedBy");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Season", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.StandingsEntry", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Team", "Team")
                        .WithMany("Standings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("League");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.StratPlayer", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.MlbPeople", "MlbPlayer")
                        .WithMany()
                        .HasForeignKey("MlbPlayerId")
                        .HasPrincipalKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StratSphere.Core.Entities.StratTeam", "StratTeam")
                        .WithMany("Players")
                        .HasForeignKey("StratTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");

                    b.Navigation("MlbPlayer");

                    b.Navigation("StratTeam");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.StratTeam", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Subleague", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany("Subleagues")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Team", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.Division", "Division")
                        .WithMany("Teams")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.User", "Owner")
                        .WithMany("Teams")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Subleague", "Subleague")
                        .WithMany("Teams")
                        .HasForeignKey("SubleagueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Division");

                    b.Navigation("League");

                    b.Navigation("Owner");

                    b.Navigation("Subleague");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Transaction", b =>
                {
                    b.HasOne("StratSphere.Core.Entities.Draft", "Draft")
                        .WithMany()
                        .HasForeignKey("DraftId");

                    b.HasOne("StratSphere.Core.Entities.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Team", "OtherTeam")
                        .WithMany()
                        .HasForeignKey("OtherTeamId");

                    b.HasOne("StratSphere.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StratSphere.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("League");

                    b.Navigation("OtherTeam");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Division", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Draft", b =>
                {
                    b.Navigation("DraftOrder");

                    b.Navigation("Picks");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.League", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Members");

                    b.Navigation("Seasons");

                    b.Navigation("Subleagues");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Player", b =>
                {
                    b.Navigation("DraftSelections");

                    b.Navigation("RosterEntries");

                    b.Navigation("ScoutingReports");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Season", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.StratTeam", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Subleague", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("DraftPicks");

                    b.Navigation("HomeGames");

                    b.Navigation("Roster");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("StratSphere.Core.Entities.User", b =>
                {
                    b.Navigation("LeagueMemberships");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
