// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stratsphere.Data;

#nullable disable

namespace Stratsphere.Data.Migrations
{
    [DbContext(typeof(StratosphereDbContext))]
    partial class StratosphereDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("GameDate")
                        .HasColumnType("date");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Lahman.LahmanBatting", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("player_id");

                    b.Property<int>("YearId")
                        .HasColumnType("integer")
                        .HasColumnName("year_id");

                    b.Property<int>("Stint")
                        .HasColumnType("integer")
                        .HasColumnName("stint");

                    b.Property<int?>("AB")
                        .HasColumnType("integer");

                    b.Property<int?>("BB")
                        .HasColumnType("integer");

                    b.Property<int?>("CS")
                        .HasColumnType("integer");

                    b.Property<int?>("Doubles")
                        .HasColumnType("integer")
                        .HasColumnName("doubles");

                    b.Property<int?>("G")
                        .HasColumnType("integer");

                    b.Property<int?>("GIDP")
                        .HasColumnType("integer")
                        .HasColumnName("g_idp");

                    b.Property<int?>("H")
                        .HasColumnType("integer");

                    b.Property<int?>("HBP")
                        .HasColumnType("integer");

                    b.Property<int?>("HR")
                        .HasColumnType("integer");

                    b.Property<int?>("IBB")
                        .HasColumnType("integer");

                    b.Property<string>("LgId")
                        .HasColumnType("text")
                        .HasColumnName("lg_id");

                    b.Property<int?>("R")
                        .HasColumnType("integer");

                    b.Property<int?>("RBI")
                        .HasColumnType("integer");

                    b.Property<int?>("SB")
                        .HasColumnType("integer");

                    b.Property<int?>("SF")
                        .HasColumnType("integer");

                    b.Property<int?>("SH")
                        .HasColumnType("integer");

                    b.Property<int?>("SO")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<int?>("Triples")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "YearId", "Stint");

                    b.ToTable("batting", "lahman");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Lahman.LahmanFielding", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("player_id");

                    b.Property<int>("YearId")
                        .HasColumnType("integer")
                        .HasColumnName("year_id");

                    b.Property<int>("Stint")
                        .HasColumnType("integer")
                        .HasColumnName("stint");

                    b.Property<string>("Pos")
                        .HasColumnType("text")
                        .HasColumnName("pos");

                    b.Property<int?>("A")
                        .HasColumnType("integer");

                    b.Property<int?>("DP")
                        .HasColumnType("integer");

                    b.Property<int?>("E")
                        .HasColumnType("integer");

                    b.Property<int?>("G")
                        .HasColumnType("integer");

                    b.Property<int?>("GS")
                        .HasColumnType("integer");

                    b.Property<int?>("InnOuts")
                        .HasColumnType("integer")
                        .HasColumnName("inn_outs");

                    b.Property<string>("LgId")
                        .HasColumnType("text")
                        .HasColumnName("lg_id");

                    b.Property<int?>("PO")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.HasKey("PlayerId", "YearId", "Stint", "Pos");

                    b.ToTable("fielding", "lahman");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Lahman.LahmanPerson", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("player_id");

                    b.Property<string>("Bats")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("bats");

                    b.Property<string>("BbrefId")
                        .HasColumnType("text")
                        .HasColumnName("bbref_id");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("integer")
                        .HasColumnName("birth_day");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("integer")
                        .HasColumnName("birth_month");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<DateOnly?>("Debut")
                        .HasColumnType("date")
                        .HasColumnName("debut");

                    b.Property<DateOnly?>("FinalGame")
                        .HasColumnType("date")
                        .HasColumnName("final_game");

                    b.Property<string>("NameFirst")
                        .HasColumnType("text")
                        .HasColumnName("name_first");

                    b.Property<string>("NameGiven")
                        .HasColumnType("text")
                        .HasColumnName("name_given");

                    b.Property<string>("NameLast")
                        .HasColumnType("text")
                        .HasColumnName("name_last");

                    b.Property<string>("RetroId")
                        .HasColumnType("text")
                        .HasColumnName("retro_id");

                    b.Property<string>("Throws")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("throws");

                    b.HasKey("PlayerId");

                    b.ToTable("people", "lahman");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Lahman.LahmanPitching", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("player_id");

                    b.Property<int>("YearId")
                        .HasColumnType("integer")
                        .HasColumnName("year_id");

                    b.Property<int>("Stint")
                        .HasColumnType("integer")
                        .HasColumnName("stint");

                    b.Property<int?>("BB")
                        .HasColumnType("integer");

                    b.Property<int?>("CG")
                        .HasColumnType("integer");

                    b.Property<int?>("ER")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ERAStored")
                        .HasColumnType("numeric")
                        .HasColumnName("era");

                    b.Property<int?>("G")
                        .HasColumnType("integer");

                    b.Property<int?>("GS")
                        .HasColumnType("integer");

                    b.Property<int?>("H")
                        .HasColumnType("integer");

                    b.Property<int?>("HR")
                        .HasColumnType("integer");

                    b.Property<int?>("IPOuts")
                        .HasColumnType("integer")
                        .HasColumnName("ip_outs");

                    b.Property<int?>("L")
                        .HasColumnType("integer");

                    b.Property<string>("LgId")
                        .HasColumnType("text")
                        .HasColumnName("lg_id");

                    b.Property<int?>("SHO")
                        .HasColumnType("integer");

                    b.Property<int?>("SO")
                        .HasColumnType("integer");

                    b.Property<int?>("SV")
                        .HasColumnType("integer");

                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("team_id");

                    b.Property<int?>("W")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "YearId", "Stint");

                    b.ToTable("pitching", "lahman");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommissionerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("setup");

                    b.HasKey("Id");

                    b.HasIndex("CommissionerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.LeagueMember", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("LeagueId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("league_members", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.PlayerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardYear")
                        .HasColumnType("integer");

                    b.Property<string>("LahmanPlayerId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("LahmanPlayerId", "CardYear", "Position")
                        .IsUnique();

                    b.ToTable("player_cards", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.RosterSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonId", "CardId")
                        .IsUnique();

                    b.ToTable("roster_slots", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CardYear")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.SimBattingStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AB")
                        .HasColumnType("integer");

                    b.Property<int>("BB")
                        .HasColumnType("integer");

                    b.Property<int>("CS")
                        .HasColumnType("integer");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Doubles")
                        .HasColumnType("integer");

                    b.Property<int>("G")
                        .HasColumnType("integer");

                    b.Property<int>("H")
                        .HasColumnType("integer");

                    b.Property<int>("HBP")
                        .HasColumnType("integer");

                    b.Property<int>("HR")
                        .HasColumnType("integer");

                    b.Property<int>("R")
                        .HasColumnType("integer");

                    b.Property<int>("RBI")
                        .HasColumnType("integer");

                    b.Property<int>("SB")
                        .HasColumnType("integer");

                    b.Property<int>("SF")
                        .HasColumnType("integer");

                    b.Property<int>("SO")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Triples")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("CardId", "SeasonId")
                        .IsUnique();

                    b.ToTable("sim_batting_stats", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.SimPitchingStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BB")
                        .HasColumnType("integer");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("ER")
                        .HasColumnType("integer");

                    b.Property<int>("G")
                        .HasColumnType("integer");

                    b.Property<int>("GS")
                        .HasColumnType("integer");

                    b.Property<int>("H")
                        .HasColumnType("integer");

                    b.Property<int>("HR")
                        .HasColumnType("integer");

                    b.Property<int>("IPOuts")
                        .HasColumnType("integer");

                    b.Property<int>("L")
                        .HasColumnType("integer");

                    b.Property<int>("SO")
                        .HasColumnType("integer");

                    b.Property<int>("SV")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("W")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("CardId", "SeasonId")
                        .IsUnique();

                    b.ToTable("sim_pitching_stats", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Standings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("RunsAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("RunsScored")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Streak")
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ties")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique();

                    b.ToTable("standings", (string)null);
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("UserId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Game", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Season", "Season")
                        .WithMany("Games")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.League", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.ApplicationUser", "Commissioner")
                        .WithMany()
                        .HasForeignKey("CommissionerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commissioner");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.LeagueMember", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.ApplicationUser", "User")
                        .WithMany("LeagueMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.RosterSlot", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.PlayerCard", "Card")
                        .WithMany("RosterSlots")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Season", "Season")
                        .WithMany("RosterSlots")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Team", "Team")
                        .WithMany("RosterSlots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Season", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.SimBattingStats", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.PlayerCard", "Card")
                        .WithMany("SimBattingStats")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.SimPitchingStats", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.PlayerCard", "Card")
                        .WithMany("SimPitchingStats")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Standings", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Team", b =>
                {
                    b.HasOne("Stratsphere.Core.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stratsphere.Core.Entities.Season", null)
                        .WithMany("Teams")
                        .HasForeignKey("SeasonId");

                    b.HasOne("Stratsphere.Core.Entities.ApplicationUser", "User")
                        .WithMany("Teams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("LeagueMemberships");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.League", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.PlayerCard", b =>
                {
                    b.Navigation("RosterSlots");

                    b.Navigation("SimBattingStats");

                    b.Navigation("SimPitchingStats");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Season", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("RosterSlots");

                    b.Navigation("Standings");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Stratsphere.Core.Entities.Team", b =>
                {
                    b.Navigation("RosterSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
